openapi: 3.0.0
info:
  title: SDC Tasks API
  version: 1.0.0
tags:
  - name: Tasks
  - name: Auth
  - name: Users
paths:
  /api/login/google:
    get:
      operationId: Auth_login
      description: If successful, the callback URL will include additional query parameters, `access_token` and `refresh_token`.
      parameters:
        - name: c
          in: query
          required: true
          description: The callback url that backend redirect back to frontend
          schema:
            type: string
          explode: false
        - name: r
          in: query
          required: false
          description: The url that frontend redirect from callback to the page user was viewing
          schema:
            type: string
          explode: false
      responses:
        '302':
          description: Redirection
        '404':
          description: The server cannot find the requested resource.
      tags:
        - Auth
  /api/logout:
    get:
      operationId: Auth_logout
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      tags:
        - Auth
  /api/refreshToken/{refreshToken}:
    get:
      operationId: Auth_refreshToken
      parameters:
        - name: refreshToken
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshTokenResponse'
      tags:
        - Auth
  /api/task:
    get:
      operationId: Tasks_getAllTasks
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'
      tags:
        - Tasks
    post:
      operationId: Tasks_createTask
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
  /api/task/{id}:
    get:
      operationId: Tasks_getTaskById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - Tasks
    put:
      operationId: Tasks_updateTask
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
    delete:
      operationId: Tasks_deleteTask
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '404':
          description: The server cannot find the requested resource.
      tags:
        - Tasks
  /api/user/me:
    get:
      operationId: Users_getMe
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SDCTasksAPI.Users.UserResponse'
      tags:
        - Users
  /api/users:
    put:
      operationId: Users_update
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SDCTasksAPI.Users.UserResponse'
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SDCTasksAPI.Users.UserUpdateRequest'
components:
  schemas:
    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
    RefreshTokenResponse:
      type: object
      required:
        - access_token
        - expiration
        - refresh_token
      properties:
        access_token:
          type: string
        expiration:
          type: integer
          format: int32
        refresh_token:
          type: string
    SDCTasksAPI.Users.UserResponse:
      type: object
      required:
        - id
        - username
        - email
        - about
        - avatarUrl
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        about:
          type: string
        avatarUrl:
          type: string
    SDCTasksAPI.Users.UserUpdateRequest:
      type: object
      required:
        - about
      properties:
        about:
          type: string
    TaskResponse:
      type: object
      required:
        - id
        - labels
        - title
        - description
        - status
        - dueDate
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
          format: int32
        labels:
          type: array
          items:
            type: string
        title:
          type: string
        description:
          type: string
        status:
          type: string
        dueDate:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    UpdateTaskRequest:
      type: object
      required:
        - title
        - description
        - status
        - dueDate
        - labels
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
        dueDate:
          type: string
        labels:
          type: array
          items:
            type: string
    Versions:
      type: string
      enum:
        - 1.0.0
servers:
  - url: https://example.com
    description: Single server endpoint
    variables: {}
